name: Generate 3D Contribution Chart

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate 3D Contribution Chart
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Abhi-lash19
          MAX_REPOS: 100
          SETTING_JSON: |
            {
              "type": "calendar",
              "backgroundColor": "#0D1117",
              "color": "#FF007F",
              "animation": true
            }

      - name: Deploy 3D Chart
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./profile-3d-contrib
          publish_branch: output
