name: Generate Contribution Globe

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      - name: Checkout output branch
        uses: actions/checkout@v3
        with:
          ref: output

=======
>>>>>>> eebe9be (updated readme file)
      - name: Generate Globe
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-contribution-globe.svg
<<<<<<< HEAD
=======
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}

>>>>>>> eebe9be (updated readme file)
          base: ""
          template: classic
          config_timezone: Asia/Kolkata

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
<<<<<<< HEAD
          config_timezone: Asia/Kolkata
          template: classic
          config_display: large

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add github-contribution-globe.svg
          git commit -m "Update contribution globe" || echo "No changes"
          git push
=======

          plugin_activity: yes
          plugin_activity_limit: 5

          plugin_languages: yes
          plugin_languages_sections: most-used
>>>>>>> eebe9be (updated readme file)
