name: Generate Contribution Globe

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Globe
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-contribution-globe.svg
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          base: ""
          template: classic
          config_timezone: Asia/Kolkata

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_activity: yes
          plugin_activity_limit: 5

          plugin_languages: yes
          plugin_languages_sections: most-used
