name: Generate Contribution Globe

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout output branch
        uses: actions/checkout@v3
        with:
          ref: output

      - name: Generate Globe
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-contribution-globe.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Asia/Kolkata
          template: classic
          config_display: large

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add github-contribution-globe.svg
          git commit -m "Update contribution globe" || echo "No changes"
          git push
